server:
  port: 8321

spring:
  application:
    name: monitoring-server
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 5
        multiplier: 1.1
        max-interval: 2000

  profiles:
    active: local  # ???? ??